#Change to MySQL for mysql support#
#Change to SQLite for sqlite support#
Database: SQLite
MYSQL:
  Database: 'jdbc:mysql://localhost:3306/minecraft'
  User: 'root'
  Password: 'root'
Places:
  stone:
    '1':
      Message: '&4Your first stone smelt!'
Breaks:
  stone:
    '1':
      Message: '&7Your first cobble!'
Kills:
  zombie:
    '1':
      Message: '&8Your first zombie!'
      Reward:
        Money:
          Amount: 1
        Item:
          Type: stone
          Amount: 1
Crafts:
  diamond_sword:
    '1':
      Message: Badass Sword!
      Reward:
        Money:
          Amount: 1
        Item:
          Type: diamond
          Amount: 1